// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Xsolla Sdk Backend
//
//  This is example server implementing some demonstration functions
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 0.0.1
//  Contact: <integration@xsolla.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
